apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/jaberchez/demo-kustomize-bases/ldap-auth?ref=openshift-4.7.3

transformers:
  - dataReplaceInline.yaml
