apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/jaberchez/demo-kustomize-bases/app/deployment?ref=openshift-4.7.3
  - https://github.com/jaberchez/demo-kustomize-bases/app/service?ref=openshift-4.7.3
  - https://github.com/jaberchez/demo-kustomize-bases/app/route?ref=openshift-4.7.3
  - https://github.com/jaberchez/demo-kustomize-bases/app/secret?ref=openshift-4.7.3

commonLabels:
  app: demo-webserver

namespace: demo-webserver

patches:
  - target:
      kind: Deployment
      name: base-name
    path: patch-deployment.json

  - target:
      kind: Service
      name: base-name
    path: patch-service.json

  - target:
      kind: Route
      name: base-name
    path: patch-route.json

  - target:
      kind: Route
      name: base-name
    path: patch-secret.json

images:
  - name: base-image
    newName: quay.io/jberchez-redhat/demo-webserver
    newTag: v1.0

patchesStrategicMerge:
  - patch-deployment-env.yaml

transformers:
  - dataReplaceInline.yaml

