apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/jaberchez/demo-kustomize-bases/app/deployment?ref=master
  - https://github.com/jaberchez/demo-kustomize-bases/app/service?ref=master

commonLabels:
  app: demo-webserver

namespace: demo-webserver

patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: demo-webserver
    target:
      kind: Deployment
      name: "base-name"

  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: demo-webserver
    target:
      kind: Deployment
      name: "base-name"

  - patch: |-
      - op: replace
        path: /metadata/name
        value: demo-webserver
    target:
      kind: Service
      name: "base-name"

images:
  - name: base-image
    newName: quay.io/jberchez-redhat/demo-webserver
    newTag: v1.0

