apiVersion: apps/v1
kind: Deployment

metadata:
  name: demo-webserver

spec:
  template:
    containers:
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name