apiVersion: apps/v1
kind: Deployment

metadata:
  name: base-name
  namespace: base-namespace

spec:
  template:
    containers:
      - name: base-image
        image: base-image:base-version
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name