kind: Namespace
metadata:
  name: vault
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: vault
        ports:
        - containerPort: 8200
        securityContext:
          runAsUser: 0
          capabilities:
            add:
              - NET_ADMIN
              - CAP_SETFCAP

# oc commands:
# oc adm policy add-scc-to-user privileged -z default
# oc adm policy add-scc-to-user anyuid -z default
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
spec:
  selector:
    app: vault
  ports:
    - protocol: TCP
      port: 8200
      targetPort: 8200
